-- ────────────────────────────────────────────────────────────
-- Theme Launcher Custom Theme for Neovim
-- Generated by Omarchist
-- ────────────────────────────────────────────────────────────

return {
  "nyoom-engineering/oxocarbon.nvim",
  config = function()
    vim.opt.background = "dark" -- or "light"
    vim.cmd.colorscheme "oxocarbon"
  end,
}